---
- name: Install Apache Webserver and PHP5
  hosts: all
  sudo: yes
  tasks:
  - name: Install Apache systems
    yum: name={{item}} state=latest
    with_items:
    - httpd
    - mod_ssl

  - name: Update Apache ServerName
    replace: dest=/etc/httpd/conf/httpd.conf regexp='#ServerName www.example.com:80' replace='ServerName {{host}}'

  - name: Install PHP and modules
    yum: name={{item}} state=latest
    with_items:
    - php
    - php-devel
    - php-mysql

  - name: Open permissions to /var/www/html
    file: path=/var/www/html state=directory recurse=yes mode=777

  - name: Start Apache
    service: name=httpd state=started
