---
- name: Install mongos
  hosts: all
  sudo: yes
  vars:
    mongos_port: 27021
    mongos_logpath: /var/log/mongodb/mongos.log
  tasks:
  - name: Add MongoDB repo file
    copy: src=mongodb-org-3.0.repo dest=/etc/yum.repos.d/

  - name: Install MongoDB
    yum: name=mongodb-org-mongos state=latest
  
#  - name: Create data directories
#    file: path={{ data_path }} state=directory recurse=yes
  
#  - name: Copy mongod config file
#    template: src=resources/etc_mongod.j2 dest=/etc/mongod_custom.conf
 
#  - name: Start mongod instances
#    shell: mongod --config /etc/mongod_custom.conf; sleep 1;

#  - name: Start mongos instance
#    shell: numactl --interleave=all mongos --configdb {{ mongos_config }} --port {{ mongos_port }} --logpath {{ mongos_logpath }} --fork
