---
- name: Install MongoDB
  hosts: all
  sudo: yes
  tasks:
  - name: Add MongoDB repo file
    copy: src=mongodb-org-3.0.repo dest=/etc/yum.repos.d/

  - name: Install MongoDB
    yum: name=mongodb-org state=latest

  - name: Create data directory
    file: path=/data/mongodb state=directory recurse=yes
  
  - name: Copy mongod config file
    template: src=etc_mongod.j2 dest=/etc/mongod_custom.conf
 
  - name: Start mongod instance
    shell: mongod --config /etc/mongod_custom.conf; sleep 1;
