---
- name: Install Lucidworks Fusion
  hosts: all
  sudo: yes
  tasks:
  - name: Install selinux-python bindings
    yum: name=libselinux-python state=latest

  - name: Disable SELinux
    selinux: state=disabled

  - name: Disable iptables
    service: name=iptables state=stopped

  - name: Install dependencies
    yum: name={{ item }} state=latest
    with_items:
    - java-1.8.0-openjdk.x86_64

  - name: Unzip packages
    unarchive: src={{ item }} dest=/opt/
    with_items:
    - deps/fusion-2.1.0.tar.gz 

  - name: Start Fusion
    command: /opt/fusion/bin/fusion start
