---
- name: Install and start MySQL Server
  hosts: all
  become: yes
  tasks:
  - name: Install MySQL Server
    yum: name=mysql-server state=present

  - name: Start MySQL Server
    service: name=mysqld state=started

  - name: Add "admin:admin" user to mysql on localhost and remote with full privileges
    script: permissions.sh
