---
- name: Base Install Couchbase
  hosts: all
  become: yes
  vars:
    couchbase_repository: http://packages.couchbase.com/releases/4.0.0
    couchbase_rpm: couchbase-server-enterprise-4.0.0-centos6.x86_64.rpm
  tasks:
  - name: Check if Couchbase RPM exists
    stat: path=/vagrant/deps/{{ couchbase_rpm | quote}}
    register: rpm
    
  - name: Download Couchbase RPM
    get_url: url={{ couchbase_repository | quote }}/{{ couchbase_rpm | quote }} dest=/vagrant/deps/
    when: rpm.stat.exists == False
            
  - name: Install Couchbase RPM
    yum: name=/vagrant/deps/{{ couchbase_rpm | quote }} state=present

  - name: Wait for Couchbase initilization
    wait_for: port=8091 delay=2

  - name: Initialize Cluster
    shell: /opt/couchbase/bin/couchbase-cli cluster-init -c 127.0.0.1:8091 --cluster-init-username=couchbase --cluster-init-password=couchbase --cluster-init-port=8091 --cluster-init-ramsize=796 --services=data,index,query
