# -*- mode: ruby -*-
# # vi: set ft=ruby :

name = "couchbase"
ip = "192.168.56.40"
playbook = "couchbase.yml"

Vagrant.configure(2) do |config|
  config.ssh.insert_key = false

  if Vagrant.has_plugin?("vagrant-hostmanager")
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.hostmanager.ignore_private_ip = false
    config.hostmanager.include_offline = false
  end

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :machine
  end

  config.vm.define name do |vmconfig|
    vmconfig.vm.box = "bento/centos-6.7"
    vmconfig.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 4
    end

    vmconfig.vm.hostname = name + ".vagrant"
    vmconfig.vm.network :private_network, ip: ip

    vmconfig.vm.provision "base", type: "ansible" do |ansible|
      ansible.playbook = "../base.yml"
    end

    vmconfig.vm.provision name, type: "ansible" do |ansible|
      ansible.playbook = playbook
    end
  end
end
