# -*- mode: ruby -*-
# # vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.ssh.insert_key = false

  if Vagrant.has_plugin?("vagrant-hostmanager")
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.hostmanager.ignore_private_ip = false
    config.hostmanager.include_offline = true
  end

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :machine
  end

  config.vm.define "solr.vagrant" do |vmconfig|
    vmconfig.vm.box = "bento/centos-6.7"
    vmconfig.vm.provider "virtualbox" do |v|
      v.memory = 12288
      v.cpus = 2
    end

    vmconfig.vm.hostname = "solr.vagrant"
    vmconfig.vm.network :private_network, ip: "192.168.56.50"

    vmconfig.vm.provision "ansible" do |ansible|
      ansible.playbook = "solr.yml"
    end
  end
end
