---
- name: Base Install Cassandra
  hosts: all
  sudo: yes
  vars:
    ip: "{{ hostvars['cassandra']['ansible_eth1']['ipv4']['address'] }}"
    version: cassandra20
  tasks:
  - name: Install Dependencies
    yum: name={{ item }} state=latest
    with_items:
    - java-1.7.0-openjdk.x86_64

  - name: Install argparse
    easy_install: name=argparse

  - name: Add Datastax repo file
    copy: src=datastax.repo dest=/etc/yum.repos.d/datastax.repo

  - name: Install Cassandra
    yum: name={{ version }} state=latest

  - name: Update Cassandra configs
    replace: "dest=/etc/cassandra/conf/cassandra.yaml regexp='{{ item.regexp }}' replace='{{ item.replace }}' backup=no"
    with_items:
    - { regexp: "rpc_address: localhost", replace: "rpc_address: 0.0.0.0" }
    - { regexp: "# broadcast_rpc_address: 1.2.3.4", replace: "broadcast_rpc_address: {{ ip }}" }
    - { regexp: "listen_address: localhost", replace: "listen_address: {{ ip }}" }
    - { regexp: '(\s.*)- seeds: "127.0.0.1"', replace: '\1- seeds: "{{ ip }}"' }

  - name: Start Cassandra
    service: name=cassandra state=started
